config/routes.rb
Rails.application.routes.draw do
  resources :bands do
    resources :albums, only: :new
  end

  resources :albums, except: [:index, :new] do
    resources :tracks, only: :new
  end

  resources :tracks,  except: [:index, :new]
  resources :users,   only: [:new, :create, :show]
  resource :session,  only: [:new, :create, :destroy]

end

app/models/album.rb
class Album < ActiveRecord::Base

  belongs_to(
    :band,
    class_name: "Band",
    foreign_key: :band_id,
    primary_key: :id
  )

  has_many(
    :tracks,
    dependent: :destroy,
    class_name: "Track",
    foreign_key: :album_id,
    primary_key: :id
  )

end

app/models/band.rb
class Band < ActiveRecord::Base

  has_many(
    :albums,
    dependent: :destroy,
    class_name: "Album",
    foreign_key: :band_id,
    primary_key: :id
  )

end

app/models/track.rb
class Track < ActiveRecord::Base

  belongs_to(
    :album,
    class_name: "Album",
    foreign_key: :album_id,
    primary_key: :id
  )

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, uniqueness: true
  # validates :email, :password_digest, :session_token, presence: true

  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    self.session_token = SecureRandom::urlsafe_base64
    save!
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def self.find_by_token(token)
    user = User.find_by_session_token(token)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    save!
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @albums = Album.all
    render :index
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
    @album = Album.new
    render :new
  end

  def edit
    @bands = Band.all
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])
    if @album.update_attributes(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      render :show # change this later
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  private
  def album_params
    params.require(:album).permit(:band_id, :album_name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    token = session[:session_token]
    return nil if self.session[:session_token].nil?
    @user ||= User.find_by_token(token)
  end

  def log_in_user!(user)
    user.reset_session_token!
    self.session[:session_token] = user.session_token
  end

  def logged_in?
    !self.session[:session_token].nil?
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      render :show # change this later
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      user_params[:email],
      user_params[:password]
    )

    if user.nil?
      flash.now[:errors] = ["Incorrect username and/or password"]
      redirect_to new_user_url
      return
    end

    log_in_user!(user)

    if user.save
      redirect_to user_url(user)
    else
      flash.now[:errors] = user.errors.full_messages
      redirect_to new_session_url
    end
  end

  def destroy
    unless current_user.nil?
      current_user.reset_session_token!
    end

    session[:session_token] = nil
    redirect_to new_user_url
  end

  def user_params
    params.require(:user).permit(:email, :password)

  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def index
    @tracks = Track.all
    render :index
  end

  def new
    @track = Track.new
    render :new
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def edit
    @albums = Album.all
    @track = Track.find(params[:id])
    render :edit
  end

  def update
    @track = Track.find(params[:id])
    if @track.update_attributes(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      render :show # change this later
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  private
  def track_params
    params.require(:track).permit(:album_id, :track_name, :lyrics)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!(@user)
      render :show # change this later
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/edit.html.erb
<h1>Edit Album: <%= @album.album_name %></h1>

<form method="POST"
      action="<%= @album.persisted? ? album_url(@album) : albums_url %>">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <input type="hidden"
         name="_method"
         value="<%= @album.persisted? ? 'PATCH' : 'POST' %>">
  <label for="album-name">Album Name: </label>

  <br>
  <input type="text" id="album-name"
         name="album[album_name]"
         value="<%= @album.album_name %>">

  <br>
  <br>
  <label for="album">Album</label>
  <select id="album" name="album[band_id]">
    <% @bands.each do |band| %>
      <% if @album.band.id == band.id %>
        <option selected disabled><%= band.name %></option>
      <% else %>
        <option value="<%= band.id %>"><%= band.name %></option>
      <% end %>
    <% end %>
  </select>

  <button type="submit">Edit Album</button>
</form>

app/views/albums/new.html.erb
<h1>Make Album</h1>

<form action="<%= albums_url %>" method="POST">
  <input type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

  <label for="band_id">Band ID</label>
  <input type="text"
         name="album[band_id]"
         id="band_id"
         value="<%= @album.band_id %>">
  <br>

  <label for="album_name">Album Name</label>
  <input type="text"
         name="album[album_name]"
         id="album_name"
         value="<%= @album.album_name %>">
  <br>

  <input type="submit">
</form>

app/views/albums/show.html.erb
<h1><%= @album.album_name %></h1>
<br>

<ul>
  <% @album.tracks.each do |track| %>
    <li><%= track.inspect %>
      <%= link_to "Show Track", track_url(track.id) %>
    </li>
  <% end %>
</ul>

<li><%= link_to "Edit", edit_album_url %></li>
<li><%= link_to "Band", band_url(@album.band) %></li>

app/views/bands/edit.html.erb
<h1>Edit Band: <%= @band.name %></h1>

<form method="POST"
      action="<%= @band.persisted? ? band_url(@band) : bands_url %>">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <input type="hidden"
         name="_method"
         value="<%= @band.persisted? ? 'PATCH' : 'POST' %>">
  <label for="band-name">Band Name: </label>

  <br>
  <input type="text" id="band-name"
         name="band[name]"
         value="<%= @band.name %>">

  <button type="submit">Edit Band</button>
</form>

app/views/bands/index.html.erb
<h1>Bands</h1>

<ul>
  <% @bands.each do |band| %>
    <li><%= band.inspect %>
    <%= link_to "Show Band", band_url(band.id) %>
    </li>
  <% end %>
</ul>

<%= link_to "Create new band", new_band_url %>

app/views/bands/new.html.erb
<h1>Make Band</h1>

<form action="<%= bands_url %>" method="POST">
  <input type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

  <label for="band_name">Name</label>
  <input type="text"
         name="band[name]"
         id="band_name"
         value="<%= @band.name %>">
  <br>

  <input type="submit">
</form>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<br>

<ul>
  <% @band.albums.each do |album| %>
    <li><%= album.inspect %>
      <%= link_to "Show Album", album_url(album.id) %>
    </li>
  <% end %>
</ul>

<li><%= link_to "Edit", edit_band_url %></li>

<li><%= link_to "All Bands", bands_url %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user.nil? %>
  <a href="<%= new_session_url %>">Log in</a>
  <a href="<%= new_user_url %>">Sign up</a>
<% else %>
  <%= current_user.email %>
  <form action="<%= session_url %>" method="post">
    <input type="hidden"
     name="authenticity_token"
     value="<%= form_authenticity_token %>">
    <input name="_method" type="hidden" value="delete" />
    <button name="button">log out</button>
  </form>
<% end %>

<%= yield %>

</body>
</html>

app/views/tracks/edit.html.erb
<h1>Edit Track: <%= @track.track_name %></h1>

<form method="POST"
      action="<%= @track.persisted? ? track_url(@track) : tracks_url %>">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <input type="hidden"
         name="_method"
         value="<%= @track.persisted? ? 'PATCH' : 'POST' %>">
  <label for="track-name">Track Name: </label>

  <br>
  <input type="text" id="track-name"
         name="track[track_name]"
         value="<%= @track.track_name %>">

  <br>
  <br>
  <label for="album">Album</label>
  <select id="album" name="track[album_id]">
    <% @albums.each do |album| %>
      <% if @track.album.id == album.id %>
        <option selected disabled><%= album.album_name %></option>
      <% else %>
        <option value="<%= album.id %>"><%= album.album_name %></option>
      <% end %>
    <% end %>
  </select>

  <br>
  <br>
  <label for="lyrics">Lyrics</label>
  <textarea id="lyrics" name="track[lyrics]"><%= @track.lyrics %></textarea>

  <button type="submit">Edit Track</button>
</form>

app/views/tracks/new.html.erb
<h1>Make Track</h1>

<form action="<%= tracks_url %>" method="POST">
  <input type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

  <label for="album_id">Album ID</label>
  <input type="text"
         name="track[album_id]"
         id="album_id"
         value="<%= @track.album_id %>">
  <br>

  <label for="track_name">Track Name</label>
  <input type="text"
         name="track[track_name]"
         id="track_name"
         value="<%= @track.track_name %>">
  <br>

  <label for="lyrics">Lyrics</label>
  <input type="text"
         name="track[lyrics]"
         id="lyrics"
         value="<%= @track.lyrics %>">
  <br>

  <input type="submit">
</form>

app/views/tracks/show.html.erb
<h1><%= @track.track_name %></h1>
<br>

<h2>Lyrics</h2>
<%= @track.lyrics %>

<li><%= link_to "Edit", edit_track_url %></li>

<li><%= link_to "Album", album_url(@track.album) %></li>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="POST">
  <input type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

  <label for="user_email">Email</label>
  <input type="text"
         name="user[email]"
         id="user_email"
         value="<%= @user.email %>">
  <br>

  <label for="user_password">Password</label>
  <input type="password"
         name="user[password]"
         id="user_password"
         value="<%= @user.password %>">
  <br>

  <input type="submit">
</form>